Setting environment varaibles for maven using lineinfile module and command module
[root@master_machine playbook]# cat install_maven.yml
---
- hosts: nodes
  tasks:
    - name: Install Maven
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz
        dest: /opt
        mode: '0755'
    - name: extract maven
      unarchive:
        src: /opt/apache-maven-3.8.4-bin.tar.gz
        dest: /opt
        remote_src: True
    - name: remove tar file
      file:
        path: /opt/apache-maven-3.8.4-bin.tar.gz
        state: absent
    - name: rename maven
      command: mv /opt/apache-maven-3.8.4 /opt/maven
    - name: adding the path in the bash rc files
      lineinfile: dest=/root/.bashrc line='export PATH=$PATH:/opt/apache-maven-3.8.4/bin' insertafter='EOF' regexp='export PATH=\$PATH:/opt/apache-maven-3.8.4/bin' state=present
    - name: Source the bash rc file
      shell: source /root/.bashrc
      remote_user: root
